db:
  image: mongo
  command: mongod --port 27018
  ports:
    - "27018:27018"
  restart: always
web:
  build: .
  volumes:
   - ./:/app
  ports:
    - "3000:3000"
  links:
    - db
  command: nodemon /app/server.js
